### ISSUE TITLE
Ruby 2.4.0 has deprecated the Fixnum class

### ISSUE THREAD

**Issue by buren** [bhollis/maruku#140]
Thanks for an awesome gem 🙇 

I recently upgraded to Ruby 2.4 and got a deprecation warning for `Fixnum`, since [thats being removed](http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html).

https://github.com/bhollis/maruku/blob/master/lib/maruku/output/to_html.rb#L852.

**Comment by distler** [comment]
See [here](https://github.com/distler/maruku/commit/c16d15a591da45ee83dd63d136a655eaa329586e).

**Comment by buren** [comment]
Thanks! Sorry for missing that 😳

**Comment by bhollis** [comment]
@distler why no PR?

**Comment by distler** [comment]
Sorry. Haven't had the time to rebase [stuff](https://github.com/bhollis/maruku/compare/master...distler:nokogiri). 

I could easily cherry-pick this one change, but I've already typed more characters in this thread than the change itself.
