### ISSUE TITLE
Markdown syntax is not processed within span-level tags.

### ISSUE THREAD

**Issue by jornvandebeek** [bhollis/maruku#31]
The markdown spec specifies "Unlike block-level HTML tags, Markdown syntax is processed within span-level tags.", yet maruku does not adhere to this rule. Any markdown within html tags seems to be ignored:  

```
Maruku.new("<span>*hello*</span>").to_html
```

Generates:

```
"<span>*hello*</span>"
```

Edit:Added code tags

**Comment by anitha0203** [comment]
<span>*hello*</span>
<p><span>*hello*</span></p>
<span>** hello <span>goodbye</span></span>
